# Site settings
title: Shelli Israelsen, Ph.D.
description: 'I have a doctoral degree in political science from Indiana University - Bloomington, where I specialized in international relations and research methodology. My research areas are conflict processes and international security. Specifically, my research interests include; gender and security/development, ethnic conflict, insurgent recruitment and interstate rivalry. My teaching interests include; international conflict, civil war, U.S. foreign policy, contentious politics, African politics and development, Southeast Asian politics, international law, research design and research methods.'
url: 'http://shelliisraelsen.com'
baseurl: ''
google_analytics: 'UA-68654939-2'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
