# Site settings
title: Shelli Israelsen
position: 'Ph.D. Candidate in Political Science'
university: 'Indiana University &mdash; Bloomington'
description: 'I specialize in International Relations and Research Methodology. My primary research areas are conflict dynamics, international security and foreign policy analysis. I also have expertise in African politics and development and international law. My research interests include gender and conflict, insurgent recruitment and governance, interstate rivalry formation, ethnic conflict and contentious politics. My teaching interests include international relations, U.S. foreign policy, interstate and intrastate war, African political economy, gender and international security and international law.'
url: 'http://shelliisraelsen.com'
baseurl: ''
google_analytics: 'UA-68654939-2'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
