# Site settings
title: Shelli Israelsen, Ph.D.
position: 'Department of Political Science'
university: 'Indiana University &mdash; Bloomington'
description: 'I have a doctoral degree in political science from Indiana University, where I specialized in international relations and research methodology. My research focuses primarily on conflict processes, international security and foreign policy analysis. Specifically, my research interests include: gender and security, ethnic conflict, insurgent recruitment and insurgent-created wartime institutions. My teaching interests include: international conflict, civil war, U.S. foreign policy, contentious politics, African politics and development, Southeast Asian politics, international law, research design and research methods.'
url: 'http://shelliisraelsen.com'
baseurl: ''
google_analytics: 'UA-68654939-2'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
